[package]
name = "gbonk"
version = "0.1.0"
authors = ["Louise <louise@zanier.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
gback = { path = "../gback" }
sdl2 = "0.34.4"
